server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: ${SECRET_KAFKA_HOST:localhost}:${SECRET_KAFKA_PORT:9092}
    consumer:
      group-id: "my-awesome-app"

  redis:
    host: localhost
    port: 6379
    cache:
      type: redis
      redis:
        time-to-live: 30000

spring.datasource.url: jdbc:postgresql://localhost:5432/EmployeeManagement
spring.datasource.username: postgres
spring.datasource.password: banana
spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
spring.jpa.show.sql: true
spring.jpa.hibernate.ddl-auto: update

servlet:
  multipart:
    enabled: true
    max-file-size: 2MB
    max-request-size: 3MB

app:
  token:
    secret: m#1212312121
    issuer: Backend